### ISSUE TITLE
 Portal redirection without installing flows

### ISSUE THREAD

**Issue by StephenKing** [lsinfo3/2016-itc-sbyod-onos-app#1]
The portal redirection (interception of an outgoing TCP connection) of an unauthenticated user should be handled without installing flows.

**Comment by StephenKing** [comment]
Hey @LorenzReinhart, could you please quickly remove all the portal interception flows? That would help me verifying the remaining functionality.

**Comment by LorenzReinhart** [comment]
Hi @StephenKing, i've removed the portal redirection using flows in the current commit.
For your information: The redirection is done at the end of the private class 'ReactivePacketProcessor' inside the 'PortalManager' class. The two different redirection strategies are in the package 'uni.wue.app.redirect' called 'ControllerRedirect' and 'FlowRedirect'

**Comment by LorenzReinhart** [comment]
The redirect is realized by intercepting the unmatched requests of a personal device. Those are send to the controller which modifies and forwards them to a specific server. This server answers with a HTTP 307 error code "Temporary Redirect". The answer is again intercepted by the controller and modified and forwarded to the personal device.
