### ISSUE TITLE
Roaming user (without PortStatus change, between switches): Activated services follow the user

### ISSUE THREAD

**Issue by StephenKing** [lsinfo3/2016-itc-sbyod-onos-app#2]
Given a user is connected to switch A
And a service is activated
When the user moves to **a different** switch B **without** triggering a PortStatus message
Then the flow rules for the activated service should be installed on switch B
And the flow rules on switch A should be adjusted or deleted.

**Comment by LorenzReinhart** [comment]
The services of a roaming personal device follow its location in the network as long as ONOS is sending a "HostMoved" or "HostUpdated" event.
