### ISSUE TITLE
Roaming user (without PortStatus change, same switch): Activated services follow the user

### ISSUE THREAD

**Issue by StephenKing** [lsinfo3/2016-itc-sbyod-onos-app#3]
Given a user is connected to a switch
And a service is activated
When the user moves to a different port of **the same** switch **without** triggering a PortStatus message
Then the flow rules for the activated service should be updated.

**Comment by LorenzReinhart** [comment]
The services of a roaming personal device follow its location in the network as long as ONOS is sending a "HostMoved" or "HostUpdated" event.
