### ISSUE TITLE
DHCP service

### ISSUE THREAD

**Issue by StephenKing** [lsinfo3/2016-itc-sbyod-onos-app#4]
The DHCP service should be configured in ONOS so that clients automatically receive an IP address.

**Comment by StephenKing** [comment]
We can use the University's DNS resolver `132.187.0.13`.

**Comment by StephenKing** [comment]
.. and if we would use `s-byod.de` as search domain, thinks could look even nicer.

**Comment by LorenzReinhart** [comment]
Hosts are receiving an IP from the default dhcp application of onos now.

**Comment by LorenzReinhart** [comment]
ONOS DHCP module allows users to request an IP address.
